name: Deploy to docker-hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: marcoastorojas
        password: Weabergey1!

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: marcoastorojas/app-prueba:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into VM and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: 144.22.194.20
        username: ubuntu
        key: ${{ secrets.VM_KEY }}
        script: |
          docker pull username/repo:tag
          docker stop <container-name> || true
          docker rm <container-name> || true
          docker run -d -p 4200:80 marcoastorojas/app-prueba


  
